use std::fs::{remove_file, File};
use std::io::{BufRead, BufReader, Result};

/// The path to the file that tracks autogenerated files.
pub const AUTOGEN_TRACKER: &str = ".autogen.txt";

/// Clean up all autogenerated files.
pub fn clean_autogen() -> Result<()> {
    match File::open(AUTOGEN_TRACKER) {
        Ok(existing_tracker) => {
            for line in BufReader::new(existing_tracker).lines() {
                let filename = line.unwrap();
                match remove_file(&filename) {
                    Ok(_) => (), // be silent on success
                    Err(_) => println!(
                        "Skipping deletion of {}. It might not exist anymore.",
                        filename
                    ),
                }
            }
            remove_file(AUTOGEN_TRACKER)?;
        }
        Err(_) => println!("No autogenerated files to clean up."),
    }
    Ok(())
}
